name: riddance_env
version: 0.0.23
description: Automate Flutter maintenance chores.
topics:
  - devenv
  - riddance
  - codegen
  - template
  - build-runner

environment:
  sdk: ^3.10.0

dependencies:
  icons_launcher: 3.0.3
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: 6.0.0
